version: '3'

services:
  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - authenticationDatabaseData:/var/lib/mysql
    networks:
      - authenticationNetwork
  authenticationDatabaseMigration:
    image: authenticationdatabasemigration
    environment:
      - DATABASE_URL=authenticationDatabase
    networks:
      - authenticationNetwork
  authenticationImg:
    image: authenticationimg
    environment:
      - DATABASE_URL=authenticationDatabase
    ports:
    - 5000:5000
    networks:
    - authenticationNetwork
  storeDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - storeDatabaseData:/var/lib/mysql
    networks:
      - customerNetwork
      - adminNetwork
      - daemonNetwork
      - storeNetwork
  storeDatabaseMigration:
    image: storedatabasemigration
    environment:
      - DATABASE_URL=storeDatabase
      - REDIS_HOST=redis
    networks:
      - storeNetwork
  redis:
    image: redis
    networks:
      - daemonNetwork
      - warehouseNetwork
  warehouseImg:
    image: warehouseimg
    environment:
      - DATABASE_URL=storeDatabase
      - REDIS_HOST=redis
    ports:
      - 5001:5001
    networks:
      - warehouseNetwork
    deploy:
      replicas: 3
  dameonImg:
    image: dameonimg
    environment:
      - DATABASE_URL=storeDatabase
      - REDIS_HOST=redis
    ports:
      - 5002:5002
    networks:
      - daemonNetwork
  customerImg:
    image: customerimg
    environment:
      - DATABASE_URL=storeDatabase
      - REDIS_HOST=redis
    ports:
      - 5003:5003
    networks:
      - customerNetwork
    deploy:
      replicas: 3
  adminImg:
    image: adminimg
    environment:
      - DATABASE_URL=storeDatabase
      - REDIS_HOST=redis
    ports:
      - 5004:5004
    networks:
      - adminNetwork

volumes:
  authenticationDatabaseData:
  storeDatabaseData:

networks:
  authenticationNetwork:
    driver: overlay
  storeNetwork:
    driver: overlay
  customerNetwork:
    driver: overlay
  adminNetwork:
    driver: overlay
  warehouseNetwork:
    driver: overlay
  daemonNetwork:
    driver: overlay