"""Izmenjena tabela OrderProducts

Revision ID: 6df7ba0948a2
Revises: 8f8b96df1f02
Create Date: 2022-06-19 20:38:07.504469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6df7ba0948a2'
down_revision = '8f8b96df1f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_ibfk_1', 'order', type_='foreignkey')
    op.drop_column('order', 'requested')
    op.drop_column('order', 'received')
    op.drop_column('order', 'productId')
    op.drop_column('order', 'productPrice')
    op.add_column('orderproduct', sa.Column('requested', sa.Integer(), nullable=False))
    op.add_column('orderproduct', sa.Column('received', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderproduct', 'received')
    op.drop_column('orderproduct', 'requested')
    op.add_column('order', sa.Column('productPrice', mysql.FLOAT(), nullable=False))
    op.add_column('order', sa.Column('productId', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('received', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('requested', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('order_ibfk_1', 'order', 'product', ['productId'], ['id'])
    # ### end Alembic commands ###
