"""Izmenjena tabela OrderProducts

Revision ID: f6ddb6f8b89b
Revises: 6df7ba0948a2
Create Date: 2022-06-19 20:45:12.625999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ddb6f8b89b'
down_revision = '6df7ba0948a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderproduct', sa.Column('productPrice', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderproduct', 'productPrice')
    # ### end Alembic commands ###
